# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1f811e156334fb2eb6c0bade82378119fd2a1ff656ea0c0965de54bdd1ccf0f93f431105906a5293abbab2e5195cc35e8837d593bd559e8ce530e920abfd0054

test:
  secret_key_base: 894bc49dcd32a0becd0d96806fcd172f95a0efb218bfe7ccf612a77eb643d6392e05130dcc93f553ab411880a9e943fdcf8e2c7892add90b6dbea5912c8b51e1

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
